spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://119.3.176.15:3306/com_smart_pots?useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      test-on-return: false
      pool-prepared-statements: true

      max-pool-prepared-statement-per-connection-size: 20


      filters: stat, wall, log4j
      connection-properties: ruid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000


      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /*.js,/*.gif,/*.jpg,/*.bmp,/*.png,/*.css,/*.ico,/druid/*

      stat-view-servlet:
        enabled: true
        deny: 119.3.176.15
        reset-enable: false
        url-pattern: /druid/*
        allow: 119.3.176.15
        login-username: root
        login-password: 738667591@qq.com

mybatis:
  #config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080
